[tool.pytest.ini_options]
pythonpath = [
    '.', 'src',
]
filterwarnings = ['ignore::UserWarning', 'ignore::DeprecationWarning:']

asyncio_mode='auto'  # need for auto-detecting async fixtures
# In auto mode pytest-asyncio automatically adds the asyncio marker to all
# asynchronous test functions. It will also take ownership of all async fixtures,
# regardless of whether they are decorated with @pytest.fixture or @pytest_asyncio.fixture.